### ISSUE TITLE
Having an issue integrating the Web API that we created from previous learning module - into Azure API Management

### ISSUE THREAD

**Issue by Gakinchi** [microsoft/Low-Code#25]
## Submitted By
gakinchi

## Your Role
> What is your role in this learning context?
Professional Developer

---

## For Product
> What do you have feedback on?
> - Swashbuckle Open API Web application
> - Azure API Management integration

https://learn.microsoft.com/en-us/training/modules/integrate-openapi-enabled-web-api-with-apim-and-visual-studio/6-exercise-integrate-web-api-with-azure-api-management

[related to the February lowcode cloudskill challenge 2023](https://learn.microsoft.com/en-us/users/cloudskillschallenge/collections/5d3khqnrpzyr?WT.mc_id=cloudskillschallenge_464c05e3-f1ae-400f-b5df-2dcd5299d347)

---

## Description
Bug Report`: Having an issue integrating the Web API that we created from previous learning module - into Azure API Management. 

---

## Details
First of, apologies in advance if this is an inappropriate channel to ask for help, but I was unable to find a way to reach out from the Microsoft Learn itself...

The Azure App Service API works all fine when published without any connection to Azure API Management, but as a connection is established from my Visual Studio, it complains when it hits the integration update to Azure API Management when I Re-publish.

The error causes some failure when using Azure API Management. It creates the resource groups and an API with empty operations.

I've been trying to look for some answers online, but I keep getting the same error (tried to redo the learning steps twice yesterday and then rewinding again three times today - without any luck unfortunately)...

I've added a couple of screenshots to compliment the error description:
![vs-hitting-publish-error-popup](https://user-images.githubusercontent.com/49122586/216784084-bd5e2b06-bb8c-4a56-9731-c3b3f28be5be.png)
![tmp-file-as-screenshot](https://user-images.githubusercontent.com/49122586/216783111-1210f109-86c9-4774-b1f3-a0cc9229d5b3.png)

This is the error from Visual Studio after Publishing:

Publish has encountered an error.
Be sure that the Startup.cs for your application is calling AddSwaggerGen from within ConfigureServices in order to generate swagger file. Visit https://go.microsoft.com/fwlink/?LinkId=2131205&CLCID=0x409 for more information.

A diagnostic log has been written to the following location:
"C:\Users\gchi\AppData\Local\Temp\tmp3891.tmp"

---
## Things I've tried:
Followed the steps exactly as is with referred outdated Swashbuckle NuGet version from the learning guide
Followed the steps exactly with updated/newest Swashbuckle NuGet version instead from scratch.
Checked for information for the related error message... Tried to DuckDuckGo it:
 - [Only description I get is that people with similar issue would rebuild the project from scratch and name it something shorter](https://github.com/dotnet/AspNetCore.Docs/issues/20330#issuecomment-722461550)
 - [Checked and verified that the AddSwaggerGen and UseSwagger
 are called from Startup.cs and using default SwaggerEndPoint in startup.cs](https://stackoverflow.com/questions/68731087/adding-swagger-leading-publish-failure-asp-net-core)
 - [Made sure there's no trailing spaces in my path and using latest Swashbuckle package version](https://learn.microsoft.com/en-us/answers/questions/731287/publishing-to-azure-from-vs2019-failed-due-to-not)

**Comment by Gakinchi** [comment]
I've made a temporary workaround and just imported the API application published as app service in Azure, and used swaggers.json payload from the swagger site, and added it to the Azure API Management manually.

But would appreciate if someone from the Team could have a look with the co-creators of the learning materials about why this is happening from Visual Studio's publishing method.

Best regards,
Ga Kin Chi

**Comment by justinyoo** [comment]
@Gakinchi Thanks for the issue! We suspected that the sample app was a bit of outdated (using .NET 5), and that would cause the issue. We've updated the sample app to use .NET 7, and it worked OK. If you still have an issue, please let us know how to reproduce the error, and we'll check that out on our ends.
